In [1]:
import pandas as pd
from Reservations_Generator_00 import MyClass
from random import seed
seed(1)

In [7]:
myclass = MyClass()
tabla = myclass.df_generator()

In [8]:
tabla

,nro,fec_emi,ori,des,leg,fec_vlo,dni,est_res,fec_ult
0,1,2022-02-16,aep,juj,aep-juj,2022-02-21,36309592,x,2022-02-21
1,2,2022-03-02,aep,nqn,aep-nqn,2022-03-15,11077911,z,2022-03-02
2,3,2022-03-06,aep,juj,aep-juj,2022-03-16,22811280,z,2022-03-06
3,4,2022-02-19,aep,sla,aep-sla,2022-02-21,29999643,x,2022-02-21
4,5,2022-02-18,aep,gig,aep-gig,2022-03-04,19100450,z,2022-02-18
...,...,...,...,...,...,...,...,...,...
84994,84995,2022-02-12,tuc,fln,tuc-fln,2022-07-25,20258965,z,2022-02-12
84995,84996,2022-02-08,cor,sde,cor-sde,2022-07-31,14639874,z,2022-02-08
84996,84997,2022-02-10,cor,sla,cor-sla,2022-06-07,14681253,z,2022-02-10
84997,84998,2022-03-01,asu,pdp,asu-pdp,2022-06-02,13848423,z,2022-03-01
84998,84999,2022-03-01,mdz,nqn,mdz-nqn,2022-08-04,22314495,z,2022-03-01

In [9]:
myclass.ages(tabla)

In [13]:
tabla.fec_vlo.value_counts()

2022-07-18    605
2022-07-28    601
2022-06-23    600
2022-08-02    596
2022-07-12    596
             ...
2022-02-07     53
2022-02-06     42
2022-09-01     24
2022-09-02     19
2022-02-05     15
Name: fec_vlo, Length: 210, dtype: int64

In [10]:
tabla

,nro,fec_emi,ori,des,leg,fec_vlo,dni,est_res,fec_ult,age
0,1,2022-02-16,aep,juj,aep-juj,2022-02-21,36309592,x,2022-02-21,28
1,2,2022-03-02,aep,nqn,aep-nqn,2022-03-15,11077911,z,2022-03-02,65
2,3,2022-03-06,aep,juj,aep-juj,2022-03-16,22811280,z,2022-03-06,43
3,4,2022-02-19,aep,sla,aep-sla,2022-02-21,29999643,x,2022-02-21,40
4,5,2022-02-18,aep,gig,aep-gig,2022-03-04,19100450,z,2022-02-18,55
...,...,...,...,...,...,...,...,...,...,...
84994,84995,2022-02-12,tuc,fln,tuc-fln,2022-07-25,20258965,z,2022-02-12,47
84995,84996,2022-02-08,cor,sde,cor-sde,2022-07-31,14639874,z,2022-02-08,65
84996,84997,2022-02-10,cor,sla,cor-sla,2022-06-07,14681253,z,2022-02-10,65
84997,84998,2022-03-01,asu,pdp,asu-pdp,2022-06-02,13848423,z,2022-03-01,64
84998,84999,2022-03-01,mdz,nqn,mdz-nqn,2022-08-04,22314495,z,2022-03-01,44

In [11]:
tabla.to_csv('tabla1')